<?xml version="1.0"?>
<robot name="husky" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find husky_description)/urdf/materials.urdf.xacro" />
  <xacro:include filename="$(find husky_description)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find husky_description)/urdf/parts.urdf.xacro" />

  <xacro:include filename="$(find husky_description)/urdf/sensors/gps.urdf.xacro" />

  <xacro:include filename="$(find husky_description)/urdf/sensors/sick_lms100.urdf.xacro" />

  <!-- PROPERTY LIST -->
  <property name="M_PI" value="3.1415926535897931" />

  <!-- Size of the base. -->
  <property name="base_x_size" value="0.98740000" />
  <property name="base_y_size" value="0.57090000" />
  <property name="base_z_size" value="0.24750000" />

  <!-- Inertial values for the base at center of mass, aligned with coordinate system. Units are kg*m^2 -->

  <xacro:property name="wheelbase" value="0.5120" />
  <xacro:property name="track" value="0.5708" /> 
  <xacro:property name="wheel_vertical_offset" value="0.03282" />

  <!-- Root node is the body of the robot. -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://husky_description/meshes/base_link.stl" />
      </geometry>
      <material name="Black" />
    </visual>
    <collision>
      <origin xyz="0 0 ${0.1578 - wheel_vertical_offset}" rpy="0 0 0" />
      <geometry>
        <!-- Make collision box slightly bigger in x and z directions. -->
        <box size = "${base_x_size+0.02} ${base_y_size} ${base_z_size + 0.02}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/DarkGrey</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <link name="base_inertia">
    <inertial>
      <mass value="33.455" />
      <origin xyz="-0.08748 -0.00085 0.09947" />
      <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197"
       iyy="1.7386" iyz="-0.001544" izz="2.0296" />
     </inertial>
   </link>

   <joint name="base_inertia_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_inertia" />
  </joint>

  <gazebo reference="base_inertia">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <xacro:husky_wheel prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>
  <xacro:husky_wheel prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>
  <xacro:husky_wheel prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>
  <xacro:husky_wheel prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:husky_wheel>

</robot>
